import Head from 'next/head'
import { ReactNode } from 'react'

import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'

type Props = {
  children: ReactNode
  title?: string
}

const DefaultLayout = ({
  children,
  title = 'SIP「スマートバイオ産業・農業基盤技術」データ連携ポータル',
}: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  )
}

export default DefaultLayout
