name: Update Integbio data

on:
  schedule:
    - cron: '00 18 * * *'

  workflow_dispatch:

jobs:
  get-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date
        id: current-date
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATE=$(date --date '18 hour ago' +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O integbio_dbcatalog.zip '${{secrets.INTEGBIO_DATABASE}}${{ steps.current-date.outputs.CURRENT_DATE }}_utf8.csv.zip'
      - name: unzip
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq integbio_dbcatalog.zip
      - name: Delete zip
        run: |
          mv 'integbio_dbcatalog_cc0_${{ steps.current-date.outputs.CURRENT_DATE }}_utf8.csv' integbio_dbcatalog.csv
          rm integbio_dbcatalog.zip

  generate-json:
    runs-on: ubuntu-latest
    needs: get-file
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./script/requirements.txt
      - name: Run script
        run: |
          python ./script/integbio-csv-to-json.py
      - name: Delete csv
        run: |
          rm integbio_dbcatalog.csv
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: update-integbio-data
          commit-message: Update integbio data
          title: Update integbio data
          branch-suffix: 'short-commit-hash'
          delete-branch: true
