name: Update SIP data

on: workflow_dispatch

jobs:
  get-file:
    runs-on: ubuntu-latest
    steps:
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O sip_database.csv ${{secrets.SIP_DATABASE}}

  generate-json:
    runs-on: ubuntu-latest
    needs: get-file
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./script/requirements.txt
      - name: Run script
        run: |
          python ./script/sip-csv-to-json.py
      - name: Delete csv
        run: |
          rm sip_database.csv
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: update-sip-data
          commit-message: Update SIP data
          title: Update SIP data
          branch-suffix: 'short-commit-hash'
          delete-branch: true
